### ISSUE TITLE
transformerRPN.py modules were missing

### ISSUE THREAD

**Issue by Rocklei-pu** [ldtho/PiFeNet#1]
Thank you very much for your great work！During my operation, the following error is prompted
`ModuleNotFoundError: No module named 'second.pytorch.models.transformerRPN'`，This error is because rpn.py introduces the transformerRPN file
https://github.com/ldtho/PiFeNet/blob/b47a9c8f1165429a99512ee466b836fb2899cf95/second/pytorch/models/rpn.py#L11
But I haven't found any files about transformerRPN.py. Can you help me solve this problem? thank you

**Comment by ldtho** [comment]
This is just an unnecessary import (maybe I missed it when cleaning the code), you can just comment this out then it should be okay.
I'll update the repo asap, thank you for pointing this out.
Appreciate it.

**Comment by ldtho** [comment]
Code updated!
