### ISSUE TITLE
Stable version of spconv for this repo 

### ISSUE THREAD

**Issue by rakshithcmu** [ldtho/PiFeNet#10]
I am not able to build spconv from source as mentioned in the README.md file due PyTorch version mismatches.
I am currently installing spconv with pip (pip install spconv-cu114) for CUDA version 11.4.

But this version of spconv does not have few methods used by PiFeNet such as - "VoxelGeneratorV2" in spconv.utils. This method has been replaced by "Point2VoxelGPU3d". Because of this the entire function signature and variables are different.

Could you please let me know the exact spconv version which works well with this repo?

Please let me know if you need any additional information.

**Comment by ldtho** [comment]
Hi @rakshithcmu, thanks for your question, this repo uses spconv 1.2.1 built from source. the spconv version you're using is 2.x, which is not compatible, I'm open for any PR if you can get it working with spconv 2.x :)

**Comment by rakshithcmu** [comment]
Hi @ldtho, thank you for your response. I later tried building spconv 1.2 from the source. Now I am able to use the repo.
