### ISSUE TITLE
about the kitti Training&Validating set split

### ISSUE THREAD

**Issue by Rocklei-pu** [ldtho/PiFeNet#4]
thank u for your great work！
I noticed that you wrote in your paper：“The training set is further split into training and validating set with a ratio of 85:15.”
This does not seem  the mainstream way of division. I do not seem to find the txt file of proportion division described in the paper.
But I find the division file of kitti [train.txt](https://github.com/ldtho/PiFeNet/blob/main/second/data/ImageSets_kitti/train.txt)[val.txt](https://github.com/ldtho/PiFeNet/blob/main/second/data/ImageSets_kitti/val.txt) ，It seems to be the mainstream way of division.
Can you provide a set split file which training and validating set with a ratio of 85:15 and a more detailed training log during your model training?

**Comment by ldtho** [comment]
You can write a small script to sample from [trainval.txt](https://github.com/ldtho/PiFeNet/blob/main/second/data/ImageSets_kitti/trainval.txt) with any ratio (e.g 85:15) and save them as train.txt and val.txt, that's what I did.
Hope this helps
