### ISSUE TITLE
about kitti viewer

### ISSUE THREAD

**Issue by gdb123** [ldtho/PiFeNet#6]
I am sure the training results are correct, but when the prediction results are displayed, the Kitti viewer does not display the ground truth bbox of car type, only pedestrians and cyclists (and the same color is displayed). Clicking on 'inference' will bring up the car-type prediction box. Why not display the car type gt box?
Which great god can help? Thank you！

我确定训练结果正确，但是当进行预测结果显示时，kitti viewer不显示car类型的ground trunth bbox，仅显示行人和骑自行车（而且显示同样的颜色），点击inference会出现car类型预测框。为什么不显示car类型gt框呢？

![image](https://user-images.githubusercontent.com/72054354/233333584-41cca72f-df8f-47b9-b5b4-4e4048c8e82d.png)

非常感谢您的回复

**Comment by ldtho** [comment]
I filtered the car class out [here](https://github.com/ldtho/PiFeNet/blob/28a1bed210426e3bfc2b219f8f07aeafb7c6e653/second/data/kitti_dataset.py#L276). Just add the car class and you'll be good to go
