### ISSUE TITLE
Google Drive links

### ISSUE THREAD

**Issue by simi-asher** [ldtho/PiFeNet#7]
Hi
Thank you for sharing your repo and providing the pretrained checkpoints. I tried to access the google drive link but it says folder has been moved to trash.

I am interested in the checkpoint [google drive](https://drive.google.com/drive/folders/1IGVV3oswFyBUxTZee10-Xzrx2rYPNyvJ?usp=sharing) and JRDB test set [detections in KITTI format](https://drive.google.com/drive/folders/1IGVV3oswFyBUxTZee10-Xzrx2rYPNyvJ?usp=sharing). Is there any way to restore these folders?

Thanks

**Comment by ldtho** [comment]
I'll update the new link as soon as I can, sorry maybe the links are expired

**Comment by ldtho** [comment]
Hi @simi-asher the checkpoints can be found [here](https://drive.google.com/drive/folders/1zQ-997yOlFlLMn2HuPt0jKAnUyDADOul?usp=share_link)
