### ISSUE TITLE
About the xyres_16_submission.config 

### ISSUE THREAD

**Issue by 1843744321mark** [ldtho/PiFeNet#8]
Hello! If I want to train and test for the pedestrian category, should I modify "Cyclist" in xyres_16_submission.config to "Pedestrian"?
 database_sampler {
      #database_info_path: "/media/starlet/LdTho/data/sets/kittiv2/kitti_dbinfos_train.pkl"
      database_info_path: "/root/autodl-tmp/PiFeNet/data/kitti/kitti_dbinfos_train.pkl"
      sample_groups {
        name_to_max_num {
          key: "Cyclist"
          value: 8
        }
      }
      database_prep_steps {
        filter_by_min_num_points {
          min_num_point_pairs {
            key: "Cyclist"
            value: 5
          }
        }
      }

**Comment by ldtho** [comment]
For pedestrian only, you can remove the configs of the 'cyclist' class and you'll be good to go

**Comment by 1843744321mark** [comment]
@ldtho Thanks for your reply! I note that the goole link is empty. Could you please upload the pretrained-model for KITTI and JRDB test sets? I can not produce the promising results.

**Comment by ldtho** [comment]
Hi @1843744321mark you can find them [here](https://drive.google.com/drive/folders/1zQ-997yOlFlLMn2HuPt0jKAnUyDADOul?usp=share_link)
